帮我写深度学习的代码，内容是将图像进行分解I=I'*S+R，其中I'是图像本身颜色。内窥镜图像，其是非朗博体。应用如下的技术路线： 
    步骤1：预处理：在 HSV 或 YCbCr 空间中检测潜在高光区域（使用亮度阈值，无需标签）。
    步骤2：初始分解：用矩阵分解（如 SVT）粗分离 R（高光）和临时 I' * S。
    步骤3：精炼：输入到 CycleGAN 风格的网络中，进行域转移（从有高光到无高光），使用合成内窥镜数据（通过渲染器生成）训练，无监督损失如循环一致性和结构相似性（SSIM）。
    步骤4：后处理：迭代优化 S（通过光顺滑假设），确保 I ≈ I' * S + R。
最终要求，将图像分解后，需要能实现I'在多帧之间有着连续性。或者说，我多帧之间光照分布不同，反射也不同。所以需要不同帧之间的I'有着本身的相似性，比如颜色什么的，需要反应本身自己的颜色，而不是受光照影响的。注意，我输入的图像是(1024, 1280, 3)的形状。你可以将其进行缩放以减小网络大小。


很好。现在训练的时候报错：
Found 2197 images in /mnt/data/publicData/MICCAI19_SCARED/train/dataset7/keyframe4/image_02/data/
Epoch 1/100:   0%|                                                                                                                                                                           | 0/549 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "/home/zhouy/Works/DepthEstimation/my-est-v1/train.py", line 410, in <module>
    main()
  File "/home/zhouy/Works/DepthEstimation/my-est-v1/train.py", line 406, in main
    trainer.train(train_loader, config['num_epochs'])
  File "/home/zhouy/Works/DepthEstimation/my-est-v1/train.py", line 295, in train
    losses = self.train_step(batch, global_step)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhouy/Works/DepthEstimation/my-est-v1/train.py", line 198, in train_step
    refined_image = self.highlight_removal_net(input_with_mask, highlight_masks)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhouy/.conda/envs/depthest_zy/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhouy/Works/DepthEstimation/my-est-v1/cyclegan_network.py", line 266, in forward
    features = encoder_layer(features)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhouy/.conda/envs/depthest_zy/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhouy/.conda/envs/depthest_zy/lib/python3.11/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "/home/zhouy/.conda/envs/depthest_zy/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhouy/.conda/envs/depthest_zy/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhouy/.conda/envs/depthest_zy/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Given groups=1, weight of size [64, 4, 7, 7], expected input[4, 5, 512, 640] to have 4 channels, but got 5 channels instead


现在报错：
(depthest_zy) zhouy@test-W790E1-CE:~/Works/DepthEstimation/my-est-v1$ python train.py --data_dir  /mnt/data/publicData/MICCAI19_SCARED/train/dataset7/keyframe4/image_02/data --epochs 100 --batch_size 2
Found 2197 images in /mnt/data/publicData/MICCAI19_SCARED/train/dataset7/keyframe4/image_02/data/
Epoch 1/100:   0%|                                                                                                                                               | 0/549 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/home/zhouy/Works/DepthEstimation/my-est-v1/train.py", line 410, in <module>
    main()
  File "/home/zhouy/Works/DepthEstimation/my-est-v1/train.py", line 406, in main
    trainer.train(train_loader, config['num_epochs'])
  File "/home/zhouy/Works/DepthEstimation/my-est-v1/train.py", line 295, in train
    losses = self.train_step(batch, global_step)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhouy/Works/DepthEstimation/my-est-v1/train.py", line 251, in train_step
    d_loss_real = self.gan_loss(real_score, real_labels)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhouy/.conda/envs/depthest_zy/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhouy/.conda/envs/depthest_zy/lib/python3.11/site-packages/torch/nn/modules/loss.py", line 720, in forward
    return F.binary_cross_entropy_with_logits(input, target,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhouy/.conda/envs/depthest_zy/lib/python3.11/site-packages/torch/nn/functional.py", line 3163, in binary_cross_entropy_with_logits
    raise ValueError("Target size ({}) must be the same as input size ({})".format(target.size(), input.size()))
ValueError: Target size (torch.Size([4, 1, 16, 20])) must be the same as input size (torch.Size([4, 1, 30, 38]))

你现在应该可以看到result的结果。为什么我使用python inference.py --input /mnt/data/publicData/MICCAI19_SCARED/train/dataset7/keyframe4/image_02/data/0000000001.png --output ./results --type image --visualize --checkpoint ./checkpoints/checkpoint_epoch_100.pth（服务器上存在这个pth文件），
但是跑出来的结果，也就是results中的结果，绘制出来的mask是一片黑？reflection也是黑色的？明明很显然有高光？并且，你的分解的依据是什么？有按照我说的要求吗？同时，分解出来的I'也不对，高光的部分完全没有被光照给体现出来，其应该体现在反射的部分或者光照分布的部分中。


现在我训练了20个epoch，并测试了模型，结果存在results中。但是十分不理想。首先，复原的不理想。其次，恢复出来的本征图像，也就是instrinsic不理想，其实在是太亮了，什么特征都没有了。必须限制亮度，同  │
│   时限制过多细节特征在shading中的出现。 